### ISSUE TITLE
using package fails due to bower 

### ISSUE THREAD

**Issue by yogeshVU** [finger563/webgme-codeeditor#15]
webgme-codeeditor@3.0.18 postinstall /home/vagrant/cpswt/c2wtng-meta/node_modules/webgme-codeeditor
> bower install

sh: 1: bower: not found
npm ERR! Linux 4.2.0-27-generic
npm ERR! argv "/home/vagrant/.nvm/versions/node/v4.5.0/bin/node" "/home/vagrant/.nvm/versions/node/v4.5.0/bin/npm" "install"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! webgme-codeeditor@3.0.18 postinstall: `bower install`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the webgme-codeeditor@3.0.18 postinstall script 'bower install'.
npm ERR! This is most likely a problem with the webgme-codeeditor package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs webgme-codeeditor
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls webgme-codeeditor
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/cpswt/c2wtng-meta/npm-debug.log

**Comment by yogeshVU** [comment]
may be one needs 
```
"dependencies": {
  "bower": "^1.5.2"
}
```

**Comment by finger563** [comment]
Let me know if that is enough, I've been simply doing `npm install -g bower` to handle that, but if that works for you then I'll add it to the dependencies.

**Comment by yogeshVU** [comment]
even I did `npm install -g bower`. but I am thinking if we can add that dependency to the package.json itself?

**Comment by finger563** [comment]
I'm not sure if installing it as a dependency gives the command line access to the `bower` command, which is why bower's documentation recommends installing it globally.

**Comment by finger563** [comment]
perhaps @pmeijer can weigh in on this?

**Comment by pmeijer** [comment]
Adding it as a dependency should solve the issue:
https://docs.npmjs.com/misc/scripts#path

Alternatively you can get rid of the postinstall and only use prepublish and publish the installed bower components on npm. (However in that case you would loose the ability to use the code-editor from github.)

**Comment by finger563** [comment]
Thanks, i'll try to set that up properly so that it will work without needing to globally install bower.
