### ISSUE TITLE
When using split screen on the same file, prevent cursor location from synchronizing across panels

### ISSUE THREAD

**Issue by DWatkins** [finger563/webgme-codeeditor#18]

**Comment by finger563** [comment]
Cursor synchronization doesn't happen; the last cursor position for that document in that panel will be scrolled into view. 

Example:

panel 1 has cursor at Line 250
panel 2 has cursor at Line 500

panel 2 is scrolled down to line 1000 ( line 500 is now out of view)

panel 1 is clicked onto line 251 and now focused.

panel 1 is edited with new text added at Line 251.

panel 2 receives updated attribute and maintains cursor position at Line 500, view of document in panel 2 automatically scrolls document until Line 500 is visible (Line 500 will now be the top line in the editor in panel 2).
